name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v2

    - name: Install dependencies
      runs: npm install

    - name: Run tests
      runs: npm test